name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Weather
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Weather
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./TestProject1
      
    - name: login 
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: arunsahu92
          password: dckr_pat_QGMPWtCpBTcRlPY-tDlF4VxtWkI
          repository: arunsahu92/dot-net-codebase
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          dockerfile: dockerfile
          push: true
          tags: arunsahu92/dot-net-codebase
          labels: arunlabel
