name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    
    - name: Build
    - shell: cmd
      run: dotnet build --no-restore
      working-directory: ./Weather
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./TestProject1
      
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./Weather/* C:/inetpub/wwwroot/dotnetcore-webapp -Recurse -Force
        iisreset /start
