name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    
    - name: Build
      run: dotnet build --no-restore
      shell: cmd
      working-directory: ./Weather
    - name: Test
      run: dotnet test --no-build --verbosity normal
      shell: cmd
      working-directory: ./TestProject1
      
    - name: Run the Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish
      shell: cmd
      working-directory: ./Weather
      
    - name: Deploy to IIS
      shell: cmd
      run: |
        xcopy /s /y .\Weather\* C:\Program Files\IIS
   
